baseURL = "http://intranet.aiotools.ovh"
languageCode = "fr-fr"
theme = "dream"
title = "AIO"
[[menu.main]]
name = "Soutenir L'activité"
url = "soutenir-l-activite"
weight = 4
[[menu.main]]
name = "Conditions Sanitaires"
url = "conditions-sanitaires"
weight = 3
[[menu.main]]
name = "Vie Ensemble"
url = "vie-ensemble"
weight = 2
[[menu.main]]
identifier = "about"
name = "Pojets de substitution"
pre = "<i class='fa fa-heart'></i>"
url = "/projets-de-substitution"
weight = 1
[params]
author = "AIO intern"
avatar = "/AIO-logo.png"
backgroundImage = "/background.jpg"
dark404Button = true
darkLinkColor = "darkseagreen"
darkNav = true
email = "florian.boudinet@aio.eu"
linkColor = "mediumaquamarine"
motto = "AIO"
siteStartYear = 2020
