baseURL = "http://intranet.aiotools.ovh"
languageCode = "fr-fr"
theme = "dream"
title = "AIO"
[params]
author = "AIO intern"
avatar = "/AIO-logo.png"
backgroundImage = "/background.jpg"
dark404Button = true
darkLinkColor = "darkseagreen"
darkNav = true
email = "florian.boudinet@aio.eu"
linkColor = "mediumaquamarine"
motto = "AIO"
siteStartYear = 2020
