baseURL = "http://proditec.aiotools.ovh"
paginate = 50
languageCode = "fr-fr"
theme = "dream"
title = "Proditec"



[[menu.main]]
name = "Catégorie 1"
url = "/cat-1/"
weight = 1
identifier = "cat-1"

[[menu.main]]
name = "Sous-Catégorie 1"
url = "/cat-1/sous-cat-1/"
weight = 1
identifier = "sous-cat-1-1"
parent = "cat-1"

[[menu.main]]
name = "Sous-Catégorie 2"
url = "/cat-1/sous-cat-2/"
weight = 1
identifier = "sous-cat-1-2"
parent = "cat-1"


[[menu.main]]
name = "Catégorie 2"
url = "/cat-2/"
weight = 2
identifier = "cat-2"

[[menu.main]]
name = "Catégorie 3"
url = "/cat-3/"
weight = 3
identifier = "cat-3"

[[menu.main]]
name = "Catégorie 4"
url = "/cat-4/"
weight = 4
identifier = "cat-4"

[[menu.main]]
name = "Catégorie 5"
url = "/cat-5/"
weight = 5
identifier = "cat-5"



[params]
author = "AIO intern"
avatar = "/proditec-logo.png"
backgroundImage = "/background.jpg"
dark404Button = true
darkLinkColor = "darkseagreen"
darkNav = false
email = "florian.boudinet@aio.eu"
linkColor = "mediumaquamarine"
motto = "AIO"
siteStartYear = 2020
custom_css = ["/css/aio.css"]
